export interface ClassInterface {  
    className: string,
    teacherName: string,
    teacherID: string,
    subject: string,
    lesson: string,
    category: string,
    batchYear: number,
    numberOfWeeks: number,
    classesPerWeek: number,
    mondayData: boolean,
    tuesdayData: boolean,
    wednesdayData: boolean,
    thursdayData: boolean,
    fridayData: boolean,
    saturdayData: boolean,
    sundayData: boolean,
    mondayTime: string,
    tuesdayTime: string,
    wednesdayTime: string,
    thursdayTime: string,
    fridayTime: string,
    saturdayTime: string,
    sundayTime: string,
    linkData: string,
    otherDetails:string
}
